// new_frontend_vue/src/components/NewsFeed.vue
<script setup>
import { ref, computed, onMounted } from 'vue'
import { GetTelegraphList, ReFleshTelegraphList } from '../../wailsjs/go/main/App.js'
import { isWails } from '../composables/useAppData.js'

const channels = [
  { source: '财联社', apiSource: '财联社电报', color: 'from-green-500 to-emerald-600' },
  { source: '新浪财经', apiSource: '新浪财经', color: 'from-blue-500 to-cyan-600' },
  { source: '外媒', apiSource: '外媒', color: 'from-purple-500 to-pink-600' },
]

const channelData = ref(channels.map((c) => ({ ...c, items: [], loading: false, error: false })))
const liveTime = ref(new Date())

function mapItem(t) {
  const title = t.title || t.content || ''
  const tags = Array.isArray(t.subjects) ? t.subjects : []
  let priority = 'medium'
  if (t.isRed) priority = 'high'
  else if (t.sentimentResult === '看涨' || t.sentimentResult === '看跌') priority = 'high'
  return {
    time: t.time || '',
    title: title.length > 80 ? title.slice(0, 80) + '...' : title,
    content: t.content || '',
    tags,
    priority,
    url: t.url,
  }
}

function getPriorityClass(p) {
  if (p === 'high') return 'border-l-red-500 bg-red-500/5'
  if (p === 'medium') return 'border-l-yellow-500 bg-yellow-500/5'
  return 'border-l-gray-500 bg-gray-500/5'
}

async function loadChannel(apiSource) {
  try {
    const raw = await GetTelegraphList(apiSource)
    const list = Array.isArray(raw) ? raw : []
    return list.map(mapItem)
  } catch {
    return []
  }
}

async function refreshChannel(apiSource) {
  if (!isWails()) return
  const ch = channelData.value.find((c) => c.apiSource === apiSource)
  if (!ch) return
  ch.loading = true
  ch.error = false
  try {
    await ReFleshTelegraphList(apiSource)
    const raw = await GetTelegraphList(apiSource)
    ch.items = Array.isArray(raw) ? raw.map(mapItem) : []
  } catch {
    ch.error = true
  } finally {
    ch.loading = false
  }
}

onMounted(() => {
  setInterval(() => { liveTime.value = new Date() }, 1000)
  if (isWails()) {
    channels.forEach((config, i) => {
      GetTelegraphList(config.apiSource)
        .then((raw) => {
          channelData.value[i].items = Array.isArray(raw) ? raw.map(mapItem) : []
          channelData.value[i].error = false
        })
        .catch(() => { channelData.value[i].error = true })
    })
  } else {
    // 非 Wails 使用占位数据
    channelData.value[0].items = [
      { time: '12:06:31', title: '财联社午间新闻播报', content: '', tags: ['快讯'], priority: 'high' },
      { time: '12:05:18', title: '央行逆回购操作', content: '', tags: ['货币政策'], priority: 'medium' },
    ]
    channelData.value[1].items = [
      { time: '12:04:49', title: '比亚迪刀片电池技术', content: '', tags: ['新能源'], priority: 'high' },
    ]
    channelData.value[2].items = [
      { time: '12:05:42', title: '监管层强调房住不炒', content: '', tags: ['政策'], priority: 'high' },
    ]
  }
})

function formatTime(d) {
  return d.toLocaleString('zh-CN', { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false })
}
</script>

<template>
  <div class="bg-slate-900/40 backdrop-blur-xl rounded-2xl border border-white/10 p-6 shadow-2xl">
    <div class="flex items-center justify-between mb-6">
      <h3 class="text-lg text-cyan-400 tracking-wide flex items-center gap-2">
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" /></svg>
        实时资讯流
      </h3>
      <span class="text-xs text-gray-500">{{ formatTime(liveTime) }}</span>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-4">
      <div v-for="(ch, chIndex) in channelData" :key="ch.apiSource" class="space-y-2">
        <div class="rounded-lg px-3 py-2 flex items-center gap-2 border border-white/10 bg-opacity-20" :class="['bg-gradient-to-r', ch.color]">
          <span class="text-sm text-white font-light flex-1">{{ ch.source }}</span>
          <button
            v-if="isWails()"
            type="button"
            class="p-1 rounded hover:bg-white/10 disabled:opacity-50"
            :disabled="ch.loading"
            title="刷新"
            @click="refreshChannel(ch.apiSource)"
          >
            <svg class="w-4 h-4 text-white" :class="ch.loading ? 'animate-spin' : ''" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" /></svg>
          </button>
          <div class="w-2 h-2 rounded-full bg-green-400 animate-pulse" />
        </div>

        <div class="space-y-2">
          <div v-if="ch.loading && !ch.items.length" class="py-8 text-center text-sm text-gray-500">加载中...</div>
          <template v-else-if="ch.items.length">
            <div
              v-for="(item, idx) in ch.items"
              :key="`${ch.apiSource}-${idx}`"
              class="border-l-2 rounded-r-lg p-3 hover:bg-white/5 transition-all cursor-pointer group"
              :class="getPriorityClass(item.priority)"
            >
              <div class="flex items-start gap-2">
                <span class="text-xs font-mono text-cyan-400 flex-shrink-0 mt-0.5">{{ item.time }}</span>
                <div class="flex-1 min-w-0">
                  <p class="text-xs text-gray-300 leading-relaxed line-clamp-2 group-hover:text-white transition-colors">{{ item.title }}</p>
                  <div v-if="item.tags.length" class="flex items-center gap-1.5 mt-2 flex-wrap">
                    <span
                      v-for="(tag, ti) in item.tags"
                      :key="ti"
                      class="px-1.5 py-0.5 bg-white/5 rounded text-[10px] text-gray-400 border border-white/10"
                    >
                      {{ tag }}
                    </span>
                  </div>
                </div>
                <svg class="w-3 h-3 text-gray-600 group-hover:text-cyan-400 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" /></svg>
              </div>
            </div>
          </template>
          <div v-else class="py-8 text-center text-sm text-gray-500">暂无资讯</div>
        </div>

        <button
          v-if="isWails()"
          type="button"
          class="w-full py-2 bg-white/5 hover:bg-white/10 rounded-lg text-xs text-gray-500 hover:text-cyan-400 transition-all border border-white/5 hover:border-cyan-500/30 disabled:opacity-50"
          :disabled="ch.loading"
          @click="refreshChannel(ch.apiSource)"
        >
          {{ ch.loading ? '刷新中...' : `刷新 ${ch.source}` }}
        </button>
      </div>
    </div>

    <div class="mt-6 pt-4 border-t border-white/10 grid grid-cols-4 gap-4">
      <div class="text-center">
        <div class="text-xs text-gray-500 mb-1">今日资讯</div>
        <div class="text-lg text-cyan-400">—</div>
      </div>
      <div class="text-center">
        <div class="text-xs text-gray-500 mb-1">重要公告</div>
        <div class="text-lg text-yellow-400">—</div>
      </div>
      <div class="text-center">
        <div class="text-xs text-gray-500 mb-1">研报更新</div>
        <div class="text-lg text-purple-400">—</div>
      </div>
      <div class="text-center">
        <div class="text-xs text-gray-500 mb-1">实时监控</div>
        <div class="text-lg text-green-400 flex items-center justify-center gap-1">
          <div class="w-2 h-2 rounded-full bg-green-400 animate-pulse" /> ON
        </div>
      </div>
    </div>
  </div>
</template>

// frontend/src/app/components/NewsFeed.tsx
import { Radio, Newspaper, Globe, Clock, ChevronRight, Sparkles, RefreshCw } from 'lucide-react';
import { useState, useEffect, useCallback } from 'react';

// Wails Go bridge
const getApp = () => (window as any)?.go?.main?.App;
const getRuntime = () => (window as any)?.runtime;

function EventsOn(eventName: string, callback: (...args: any[]) => void) {
  getRuntime()?.EventsOn?.(eventName, callback);
}
function EventsOff(...eventNames: string[]) {
  getRuntime()?.EventsOff?.(...eventNames);
}

interface Telegraph {
  ID: number;
  time: string;
  dataTime: string;
  title: string;
  content: string;
  subjects: string[];
  isRed: boolean;
  url: string;
  source: string;
  sentimentResult: string;
}

const CHANNELS = [
  { source: '财联社电报', label: '财联社电报', icon: Radio,     color: 'from-green-500 to-emerald-600', event: 'newTelegraph' },
  { source: '新浪财经',   label: '新浪财经',   icon: Newspaper, color: 'from-blue-500 to-cyan-600',    event: 'newSinaNews' },
  { source: '外媒',       label: '外媒资讯',   icon: Globe,     color: 'from-purple-500 to-pink-600',  event: 'tradingViewNews' },
];

function ChannelCard({ source, label, icon: Icon, color, event }: typeof CHANNELS[0]) {
  const [items, setItems] = useState<Telegraph[]>([]);
  const [loading, setLoading] = useState(false);

  const load = useCallback((refresh = false) => {
    const App = getApp();
    if (!App) return;
    setLoading(true);
    const fn = refresh ? App.ReFleshTelegraphList : App.GetTelegraphList;
    fn(source)
      .then((res: Telegraph[] | null) => {
        if (res) setItems(res);
      })
      .finally(() => setLoading(false));
  }, [source]);

  useEffect(() => { load(false); }, [load]);

  // Listen for real-time news updates from backend
  useEffect(() => {
    const handler = (data: Telegraph[]) => {
      // Only update if data is for this source
      if (data && data.length > 0 && data[0]?.source === source) {
        setItems(data);
      }
    };
    EventsOn(event, handler);
    return () => { EventsOff(event); };
  }, [event, source]);

  const getSentimentStyle = (s: string) => {
    if (s === '看涨') return 'text-red-400 border-red-500/30 bg-red-500/10';
    if (s === '看跌') return 'text-green-400 border-green-500/30 bg-green-500/10';
    return 'text-gray-400 border-white/10 bg-white/5';
  };

  return (
    <div className="bg-slate-800/30 backdrop-blur rounded-xl border border-white/5 p-2.5 sm:p-3 hover:border-cyan-500/30 transition-all flex flex-col">
      {/* 频道标题 */}
      <div className="flex items-center justify-between mb-2 pb-1.5 border-b border-white/5">
        <div className="flex items-center gap-1.5">
          <div className={`w-1 h-1 sm:w-1.5 sm:h-1.5 rounded-full bg-gradient-to-r ${color}`}></div>
          <Icon className="w-3.5 h-3.5 text-gray-400" />
          <h4 className="text-xs sm:text-sm font-medium text-gray-300">{label}</h4>
          <span className="text-[10px] text-gray-500">{items.length}条</span>
        </div>
        <button
          onClick={() => load(true)}
          disabled={loading}
          className="p-1 rounded hover:bg-white/10 text-gray-500 hover:text-cyan-400 transition-all disabled:opacity-40"
          title="刷新"
        >
          <RefreshCw className={`w-3 h-3 ${loading ? 'animate-spin' : ''}`} />
        </button>
      </div>

      {/* 新闻列表 */}
      <div className="space-y-0.5 sm:space-y-1 flex-1 overflow-y-auto max-h-72">
        {items.length === 0 && !loading && (
          <p className="text-[10px] text-gray-500 text-center py-4">暂无数据</p>
        )}
        {loading && items.length === 0 && (
          <p className="text-[10px] text-gray-500 text-center py-4">加载中...</p>
        )}
        {items.map((item) => (
          <div
            key={item.ID}
            className="p-1.5 rounded-lg hover:bg-slate-700/30 transition-all cursor-pointer group"
          >
            <div className="flex items-start gap-1.5">
              <span className={`text-[9px] sm:text-[10px] font-mono flex-shrink-0 mt-0.5 ${item.isRed ? 'text-red-400' : 'text-cyan-400'}`}>
                {item.time}
              </span>
              <div className="flex-1 min-w-0">
                {item.title ? (
                  <p className={`text-[10px] sm:text-[11px] font-medium leading-snug line-clamp-1 md:line-clamp-none group-hover:text-white transition-colors ${
                    item.isRed ? 'text-red-300' : 'text-gray-200'
                  }`}>
                    {item.title}
                  </p>
                ) : null}
                <p className="text-[10px] sm:text-[11px] text-gray-400 leading-relaxed line-clamp-2 md:line-clamp-none group-hover:text-gray-300 transition-colors mt-0.5">
                  {item.content}
                </p>
                {/* 标签行 */}
                {((item.subjects && item.subjects.length > 0) || item.sentimentResult || item.url) && (
                  <div className="flex items-center gap-1 mt-0.5 flex-wrap">
                    {item.subjects?.slice(0, 3).map((tag, i) => (
                      <span key={i} className="px-1 py-0.5 bg-white/5 rounded text-[8px] sm:text-[9px] text-gray-400 border border-white/10">
                        {tag}
                      </span>
                    ))}
                    {item.sentimentResult && (
                      <span className={`px-1 py-0.5 rounded text-[8px] sm:text-[9px] border ${getSentimentStyle(item.sentimentResult)}`}>
                        {item.sentimentResult}
                      </span>
                    )}
                    {item.url && (
                      <a
                        href={item.url}
                        target="_blank"
                        rel="noreferrer"
                        className="px-1 py-0.5 bg-white/5 rounded text-[8px] sm:text-[9px] text-cyan-500 border border-white/10 hover:text-cyan-300"
                        onClick={e => e.stopPropagation()}
                      >
                        原文
                      </a>
                    )}
                  </div>
                )}
              </div>
              <ChevronRight className="w-2.5 h-2.5 sm:w-3 sm:h-3 text-gray-600 group-hover:text-cyan-400 group-hover:translate-x-0.5 transition-all flex-shrink-0 mt-0.5" />
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export function NewsFeed() {
  const [now, setNow] = useState(() => new Date().toLocaleString('zh-CN', { hour12: false }));

  useEffect(() => {
    const timer = setInterval(() => {
      setNow(new Date().toLocaleString('zh-CN', { hour12: false }));
    }, 1000);
    return () => clearInterval(timer);
  }, []);

  return (
    <div className="bg-slate-900/40 backdrop-blur-xl rounded-2xl border border-white/10 p-4 sm:p-5 shadow-2xl">
      <div className="flex items-center justify-between mb-3 sm:mb-4">
        <h3 className="text-base sm:text-lg text-cyan-400 tracking-wide flex items-center gap-2">
          <Sparkles className="w-4 h-4 sm:w-5 sm:h-5" />
          实时资讯流
        </h3>
        <div className="flex items-center gap-2 text-xs text-gray-500">
          <Clock className="w-3.5 h-3.5" />
          <span className="text-[10px] sm:text-xs">{now}</span>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-3 sm:gap-4">
        {CHANNELS.map(ch => (
          <ChannelCard key={ch.source} {...ch} />
        ))}
      </div>
    </div>
  );
}
